name: CI Dev(Linux)

on:
  push:
    branches: 
      - '**'        # matches every branch
      - '!master'   # excludes master
  pull_request:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        
      - name: Prepare Systemt Library
        run: sudo apt-get update && sudo apt-get install libsasl2-dev

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@ce325b60658c1b38465c06cc965b79baf32c1e72
      
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
          
      - name: Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture --quiet
