name: TelegramNotify
jobs:

  Notify_change:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          [${{ github.REPOSITORY }}][${{ github.EVENT_NAME }}][${{ github.REF_NAME }}][${{job.status}}] - COMMIT:[${{ github.event.head_commit.message }}] - SHA:${{ github.SHA }} by ${{github.ACTOR}}.

on:
  push:
  pull_request:
    types: [opened,closed]
  issues:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]
  watch:
    types: [started]
